# Generated by Django 3.0.8 on 2020-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/', verbose_name='Изображение курса'),
        ),
    ]
