# Generated by Django 3.0.8 on 2020-07-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='long_description',
            field=models.TextField(default='LONG DESCRIPTION', verbose_name='Детальное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='SHORT DESCRIPTION', max_length=255, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
