# Generated by Django 3.0.8 on 2020-07-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_coursemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название секции')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='backend.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'секции курсов',
                'db_table': 'sections',
            },
        ),
    ]
