# Generated by Django 3.0.8 on 2020-07-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_coursesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': 'секция курса', 'verbose_name_plural': 'секции курсов'},
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название урока')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='backend.CourseSection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'урок в секции курса',
                'verbose_name_plural': 'уроки в секции курса',
                'db_table': 'units',
            },
        ),
    ]
